# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

trigger:
  branches:
    include:
      - main
      - develop
      - release-*
  paths:
    exclude:
      - .gitignore
      - CHANGELOG.md
      - LICENSE.md
      - README.md
      - NuGet.Config
      - assets/*
      - .github/*

# PR always trigger build
pr:
  autoCancel: true

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

pool:
  vmImage: 'windows-latest'

variables:
  - group: sign-client-credentials
  - name: DOTNET_NOLOGO
    value: true  
  - name: buildPlatform
    value: 'Any CPU'  
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: 'nanoFramework.System.Device.Gpio.sln'
  - name: nugetPackageName
    value: 'nanoFramework.System.Device.Gpio'

# step from template @ nf-tools repo
# all build, update and publish 
steps:
- template: azure-pipelines-templates/class-lib-build.yml@templates
  parameters:
    sonarCloudProject: 'nanoframework_lib-System.Device.Gpio'

# update dependents
- template: azure-pipelines-templates/update-dependents.yml@templates  
  parameters:
    ${{ if eq(variables['UPDATE_DEPENDENTS'], 'false') }}:
      waitBeforeUpdate: false
    ${{ else }}:
      waitBeforeUpdate: true
    repositoriesToUpdate: |
      System.Device.Spi

# report build failure to Discord
- template: azure-pipelines-templates/discord-webhook-task.yml@templates
  parameters:
    status: 'failure'
    webhookUrl: '$(DiscordWebhook)'
    message: ''
